AllCops:
  Exclude:
    - vendor/**/*
    - Guardfile
  TargetRubyVersion: 1.9

Metrics/LineLength:
  Max: 120
Metrics/ParameterLists:
  Enabled: false
Style/WordArray:
  Enabled: false
AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
Style/Alias:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
PerceivedComplexity:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/HashSyntax:
  Enabled: false
